#!/usr/bin/env python3
# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def inventory_fortigate_sensors(info):
    return [(None, None)]


def check_fortigate_sensors(item, params, info):
    amount_of_sensors = []
    sensors_in_alarm = []

    for name, value, dev_status in info:
        if not name:
            continue

        if dev_status == "1":
            yield 2, "%s Alarm" % name
        else:
            yield 0, "%s OK" % name


check_info["fortigate_sensors"] = {
    "inventory_function": inventory_fortigate_sensors,
    "check_function": check_fortigate_sensors,
    "service_description": "Sensor Summary",
    "snmp_info": (
        ".1.3.6.1.4.1.12356.101.4.3.2.1",
        [
            "2",  # FORTINET-FORTIGATE-MIB::fgHwSensorEntName
            "3",  # FORTINET-FORTIGATE-MIB::fgHwSensorEntValue
            "4",  # FORTINET-FORTIGATE-MIB::fgHwSensorEntAlarmStatus
        ],
    ),
    "snmp_scan_function": lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(
        ".1.3.6.1.4.1.12356.101.1."
    ),
}
